version: '3'

services:

  powerup:
    container_name: powerup
    image: brianoflondon/hive-daily-power-up
    env_file:
      - ".env"
    environment:
      - FORCE_COLOR=1
    restart:
      always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
